package ma.azdad.model;

public enum Role {
	ROLE_IT_MANAGER,
	ROLE_PM,
	// apps
	ROLE_APPS,
	// iadmin
	ROLE_IADMIN,
	ROLE_IADMIN_ADMIN,
	// ibuy
	ROLE_IBUY,
	ROLE_IBUY_ADMIN,
	ROLE_IBUY_ASSISTANT,
	// invoice
	ROLE_INVOICE,
	ROLE_INVOICE_ADMIN,
	// iexpense
	ROLE_IEXPENSE,
	ROLE_IEXPENSE_RECEIVE_EXPENSE,
	// myhr
	ROLE_MYHR,
	ROLE_HR,
	ROLE_RH,
	ROLE_HR_INSSURANCE,
	ROLE_HR_PAYROLL,
	// my reports
	ROLE_MYREPORTS,
	ROLE_MR_EXEC,
	ROLE_MR_HR,
	ROLE_MR_KAM,
	ROLE_MR_LOB,
	ROLE_MR_PM,
	ROLE_MR_PMA,
	ROLE_MR_FA,
	// my tools
	ROLE_MYTOOLS,
	ROLE_MT_ADMIN,
	ROLE_MT_LM,
	ROLE_MT_LOM,
	ROLE_MT_USE_TOOLS,
	// ifinance
	ROLE_IFINANCE,
	ROLE_IFINANCE_USER,
	ROLE_IFINANCE_TM,
	ROLE_IFINANCE_BS,
	ROLE_IFINANCE_EX,
	// sdm
	ROLE_SDM,
	ROLE_SDM_ADMIN,
	ROLE_SDM_ASSISTANT,
	ROLE_SDM_COORDINATOR,
	ROLE_SDM_PM,
	// my office
	ROLE_MYOFFICE,
	ROLE_MYOFFICE_USER,
	ROLE_MYOFFICE_ADMIN,
	ROLE_MYOFFICE_TR_MANAGER,
	ROLE_MYOFFICE_SUPERVISOR,
	ROLE_MYOFFICE_DRIVER,
	// ilogistics
	ROLE_ILOGISTICS,
	ROLE_ILOGISTICS_ADMIN,
	ROLE_ILOGISTICS_PM,
	ROLE_ILOGISTICS_SE,
	ROLE_ILOGISTICS_TM,
	ROLE_ILOGISTICS_USER,
	ROLE_ILOGISTICS_WM,
	ROLE_ILOGISTICS_DN_NOTIFICATION,
	ROLE_ILOGISTICS_COLLECT_GOODS,
	ROLE_ILOGISTICS_HM,
	ROLE_ILOGISTICS_RECEIVE_GOODS,
	ROLE_ILOGISTICS_DELIVER_GOODS,
	// compta
	ROLE_COMPTA,
	ROLE_COMPTA_ADMIN,
	// mypm
	ROLE_MYPM,
	// myproject
	ROLE_MYPROJECT,
	// wtr
	ROLE_WTR;

	public String getRole() {
		return name().replace("ROLE_", "");
	}
}